# auth-service Helm Values
replicaCount: 2
image:
  repository: cuba-erp/auth-service
  tag: "latest"
fullnameOverride: "auth-service"
service:
  grpcPort: 50051
  metricsPort: 9090
env:
  RUST_LOG: "info"
  DATABASE_URL: "postgres://postgres:postgres@cuba-postgres.default.svc.cluster.local:5432/cuba_iam_auth"
resources:
  limits: {cpu: 500m, memory: 512Mi}
  requests: {cpu: 100m, memory: 128Mi}
