# fd-service Helm Values
replicaCount: 2
image:
  repository: cuba-erp/fd-service
  tag: "latest"
fullnameOverride: "fd-service"
service:
  grpcPort: 50044
  metricsPort: 9090
env:
  RUST_LOG: "info"
  DATABASE_URL: "postgres://postgres:postgres@cuba-postgres.default.svc.cluster.local:5432/cuba_cs_fd"
resources:
  limits: {cpu: 500m, memory: 512Mi}
  requests: {cpu: 100m, memory: 128Mi}
