# gs-service Helm Values
replicaCount: 2
image:
  repository: cuba-erp/gs-service
  tag: "latest"
fullnameOverride: "gs-service"
service:
  grpcPort: 50086
  metricsPort: 9090
env:
  RUST_LOG: "info"
  DATABASE_URL: "postgres://postgres:postgres@cuba-postgres.default.svc.cluster.local:5432/cuba_am_gs"
resources:
  limits: {cpu: 500m, memory: 512Mi}
  requests: {cpu: 100m, memory: 128Mi}
