# wc-service Helm Values
replicaCount: 2
image:
  repository: cuba-erp/wc-service
  tag: "latest"
fullnameOverride: "wc-service"
service:
  grpcPort: 50046
  metricsPort: 9090
env:
  RUST_LOG: "info"
  DATABASE_URL: "postgres://postgres:postgres@cuba-postgres.default.svc.cluster.local:5432/cuba_cs_wc"
resources:
  limits: {cpu: 500m, memory: 512Mi}
  requests: {cpu: 100m, memory: 128Mi}
