# IAM-specific Kubernetes resources
# Note: cuba-iam namespace is defined in namespaces.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proto-descriptor
  namespace: istio-system
binaryData:
  proto.pb: |
    # Base64 encoded proto.pb will be generated during deployment
---
# Service Account for IAM services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-service-account
  namespace: cuba-iam
